# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Bitcoin Pulse
email: info@bitcoinpulse.com
description: > # this means to ignore newlines until "baseurl:"
  Bitcoin Pulse tracks an assortment of metrics related to the Bitcoin ecosystem.
  We have unique charts showing the interest around Bitcoin.
  Our goal is to empower existing and potential Bitcoin users and help foster Bitcoin.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://bitcoinpulse.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
